In [2]:
import sys
import os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pd.set_option('display.max_rows', None)

In [4]:
anime_raw = pd.read_csv(r'data/anime.csv')
animelist_raw = pd.read_csv(r'data/animelist.csv')

In [5]:
anime = anime_raw.sample(n=100000, replace=True, random_state=42).copy()
animelist = animelist_raw.sample(n=100000, replace=True, random_state=42).copy()

In [6]:
animelist_raw.head()

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4
3        0      4898       0                1                 1
4        0        21      10                1                 0

In [7]:
anime.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'English name', 'Japanese name',
       'Type', 'Episodes', 'Aired', 'Premiered', 'Producers', 'Licensors',
       'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Favorites', 'Watching', 'Completed', 'On-Hold', 'Dropped',
       'Plan to Watch', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1'],
      dtype='object')

In [8]:
anime.dtypes

MAL_ID            int64
Name             object
Score            object
Genres           object
English name     object
Japanese name    object
Type             object
Episodes         object
Aired            object
Premiered        object
Producers        object
Licensors        object
Studios          object
Source           object
Duration         object
Rating           object
Ranked           object
Popularity        int64
Members           int64
Favorites         int64
Watching          int64
Completed         int64
On-Hold           int64
Dropped           int64
Plan to Watch     int64
Score-10         object
Score-9          object
Score-8          object
Score-7          object
Score-6          object
Score-5          object
Score-4          object
Score-3          object
Score-2          object
Score-1          object
dtype: object

In [15]:
anime['Duration'].unique()

array(['4 min.', '22 min. per ep.', '24 min. per ep.', '30 sec. per ep.',
       '20 min. per ep.', '24 min.', '26 min.', '23 min. per ep.',
       '5 min.', '3 min. per ep.', '7 min.', 'Unknown', '30 min. per ep.',
       '25 min. per ep.', '30 min.', '10 min.', '13 min.', '43 min.',
       '2 min.', '1 hr. 24 min.', '16 min. per ep.', '4 min. per ep.',
       '46 min.', '3 min.', '1 hr. 53 min.', '57 sec.', '5 min. per ep.',
       '8 min.', '47 min.', '1 hr. 38 min.', '1 min.', '1 min. per ep.',
       '1 hr. 21 min.', '1 hr. 39 min.', '1 hr. 20 min.',
       '9 min. per ep.', '25 min.', '51 min.', '14 min. per ep.',
       '1 hr. 14 min.', '43 min. per ep.', '1 hr. 40 min.', '30 sec.',
       '9 min.', '59 min.', '1 hr. 58 min.', '28 min.', '11 min. per ep.',
       '12 min. per ep.', '16 min.', '2 min. per ep.', '1 hr. 34 min.',
       '23 min.', '15 min. per ep.', '38 sec.', '40 min.', '32 min.',
       '15 min.', '1 hr. 32 min.', '1 hr. 8 min.', '1 hr. 15 min.',
       '1 hr. 31 min.', '17 min.', '38 min.', '1 hr. 56 min.', '1 hr.',
       '51 sec. per ep.', '15 sec.', '37 min. per ep.', '13 min. per ep.',
       '31 min.', '58 min.', '12 min.', '11 min.', '1 hr. 10 min.',
       '1 hr. 30 min.', '1 hr. 37 min.', '21 min.', '27 min. per ep.',
       '28 min. per ep.', '1 hr. 25 min.', '45 min. per ep.', '44 min.',
       '27 min.', '1 hr. 22 min.', '45 sec.', '53 min.',
       '29 min. per ep.', '1 hr. 11 min.', '20 min.', '1 hr. 44 min.',
       '36 min. per ep.', '1 hr. 50 min.', '1 hr. 23 min.',
       '1 hr. 9 min.', '41 min. per ep.', '26 min. per ep.', '48 min.',
       '29 min.', '1 hr. 45 min.', '45 min.', '41 sec.', '22 min.',
       '1 hr. 59 min.', '25 sec. per ep.', '52 min.', '33 min.',
       '47 min. per ep.', '55 min. per ep.', '10 min. per ep.', '34 min.',
       '7 min. per ep.', '6 min.', '8 min. per ep.', '1 hr. 35 min.',
       '14 min.', '50 min.', '1 hr. 54 min.', '18 min.',
       '44 sec. per ep.', '57 min.', '1 hr. 55 min.', '35 sec.',
       '46 min. per ep.', '19 min.', '35 sec. per ep.', '21 min. per ep.',
       '2 hr.', '34 min. per ep.', '28 sec.', '50 min. per ep.',
       '49 min. per ep.', '1 hr. 27 min.', '17 min. per ep.',
       '1 hr. 41 min.', '56 min.', '55 min.', '2 hr. 1 min.',
       '32 min. per ep.', '2 hr. 41 min.', '1 hr. 5 min.',
       '1 hr. 12 min.', '49 min.', '40 min. per ep.', '42 min. per ep.',
       '47 sec.', '1 hr. 13 min.', '1 hr. 7 min.', '34 sec. per ep.',
       '6 min. per ep.', '51 min. per ep.', '2 hr. 5 min.', '54 min.',
       '1 hr. 42 min.', '15 sec. per ep.', '1 hr. 17 min.', '35 min.',
       '1 hr. 51 min.', '2 hr. 33 min.', '33 min. per ep.',
       '1 hr. 18 min.', '54 min. per ep.', '1 hr. 29 min.',
       '1 hr. 46 min.', '2 hr. 6 min.', '31 sec.', '1 hr. 28 min.',
       '20 sec. per ep.', '41 min.', '1 hr. per ep.', '1 hr. 16 min.',
       '45 sec. per ep.', '1 hr. 38 min. per ep.', '18 min. per ep.',
       '42 sec.', '1 hr. 47 min.', '19 min. per ep.', '19 sec.',
       '1 hr. 36 min.', '1 hr. 3 min.', '51 sec.', '24 sec. per ep.',
       '2 hr. 10 min.', '57 sec. per ep.', '39 min.',
       '1 hr. 36 min. per ep.', '39 sec.', '35 min. per ep.',
       '1 hr. 14 min. per ep.', '26 sec. per ep.', '1 hr. 48 min.',
       '16 sec.', '36 sec.', '29 sec.', '1 hr. 2 min.', '42 sec. per ep.',
       '58 sec. per ep.', '33 sec.', '1 hr. 57 min.', '1 hr. 33 min.',
       '1 hr. 4 min.', '40 sec.', '24 sec.', '2 hr. 2 min.',
       '1 hr. 30 min. per ep.', '40 sec. per ep.', '1 hr. 43 min.',
       '2 hr. 20 min.', '44 min. per ep.', '12 sec.', '14 sec.',
       '10 sec.', '2 hr. 14 min.', '2 hr. 28 min.',
       '1 hr. 17 min. per ep.', '37 min.', '1 hr. 52 min.',
       '31 min. per ep.', '1 hr. 26 min.', '3 sec.', '1 hr. 49 min.',
       '42 min.', '37 sec.', '2 hr. 15 min.', '52 sec.',
       '21 sec. per ep.', '50 sec. per ep.', '54 sec.', '1 hr. 1 min.',
       '53 sec. per ep.', '53 min. per ep.', '1 hr. 19 min.',
       '39 min. per ep.', '1 hr. 35 min. per ep.', '52 min. per ep.',
       '46 sec.', '39 sec. per ep.', '2 hr. 3 min.', '33 sec. per ep.',
       '27 sec.', '1 hr. 16 min. per ep.', '32 sec. per ep.', '55 sec.',
       '2 hr. 40 min.', '1 hr. 6 min.', '36 sec. per ep.', '20 sec.',
       '38 min. per ep.', '2 hr. 30 min.', '2 hr. 4 min.',
       '2 hr. 17 min.', '41 sec. per ep.', '36 min.', '2 hr. 7 min.',
       '17 sec.', '37 sec. per ep.', '49 sec.', '2 hr. 21 min.',
       '1 hr. 27 min. per ep.', '14 sec. per ep.', '58 min. per ep.',
       '32 sec.', '43 sec. per ep.', '49 sec. per ep.', '2 hr. 11 min.',
       '2 hr. 27 min.', '28 sec. per ep.', '48 min. per ep.', '50 sec.',
       '2 hr. 16 min.', '1 hr. 24 min. per ep.', '1 hr. 9 min. per ep.',
       '6 sec. per ep.', '44 sec.', '22 sec. per ep.', '2 hr. 19 min.',
       '25 sec.', '2 hr. 47 min.', '57 min. per ep.', '56 sec. per ep.',
       '46 sec. per ep.', '6 sec.', '23 sec.', '2 hr. 8 min.',
       '2 hr. 43 min.', '34 sec.', '1 hr. 2 min. per ep.', '7 sec.',
       '13 sec.', '31 sec. per ep.', '2 hr. 32 min.', '22 sec.',
       '1 hr. 7 min. per ep.', '16 sec. per ep.', '18 sec. per ep.',
       '43 sec.', '2 hr. 36 min.', '2 hr. 42 min.',
       '1 hr. 5 min. per ep.', '38 sec. per ep.', '58 sec.',
       '1 hr. 11 min. per ep.', '2 hr. 12 min.', '10 sec. per ep.',
       '55 sec. per ep.', '1 hr. 15 min. per ep.', '23 sec. per ep.',
       '29 sec. per ep.', '21 sec.', '54 sec. per ep.', '12 sec. per ep.',
       '1 hr. 52 min. per ep.'], dtype=object)

In [23]:
anime['Favorites'].unique()

array([    3,   377,   393, ...,   631, 26522,  4058])

In [ ]:
animelist.columns

Index(['user_id', 'anime_id', 'rating', 'watching_status', 'watched_episodes'], dtype='object')

In [ ]:
animelist.dtypes

user_id             int64
anime_id            int64
rating              int64
watching_status     int64
watched_episodes    int64
dtype: object

In [ ]:
anime.columns = (
    anime.columns
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)
anime.columns

Index(['mal_id', 'name', 'score', 'genres', 'english_name', 'japanese_name',
       'type', 'episodes', 'aired', 'premiered', 'producers', 'licensors',
       'studios', 'source', 'duration', 'rating', 'ranked', 'popularity',
       'members', 'favorites', 'watching', 'completed', 'on_hold', 'dropped',
       'plan_to_watch', 'score_10', 'score_9', 'score_8', 'score_7', 'score_6',
       'score_5', 'score_4', 'score_3', 'score_2', 'score_1'],
      dtype='object')

In [ ]:
anime_filtered = anime[['mal_id', 'name', 'score', 'genres', 'english_name', 'japanese_name', 'type', 'episodes', 'aired', 'premiered', 'producers', 'licensors', 'studios', 'source', 'duration', 'rating', 'ranked', 'popularity', 'members', 'favorites', 'watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch', 'score_10', 'score_9', 'score_8', 'score_7', 'score_6', 'score_5', 'score_4', 'score_3', 'score_2', 'score_1']].rename(columns={'mal_id': 'anime_id'})

In [ ]:
anime_filtered.dtypes

anime_id          int64
name             object
score            object
genres           object
english_name     object
japanese_name    object
type             object
episodes         object
aired            object
premiered        object
producers        object
licensors        object
studios          object
source           object
duration         object
rating           object
ranked           object
popularity        int64
members           int64
favorites         int64
watching          int64
completed         int64
on_hold           int64
dropped           int64
plan_to_watch     int64
score_10         object
score_9          object
score_8          object
score_7          object
score_6          object
score_5          object
score_4          object
score_3          object
score_2          object
score_1          object
dtype: object

In [ ]:
import pandas as pd
import numpy as np

def convert_to_numeric_64(df):
    df_new = df.copy()

    for col in df_new.columns:
        converted = pd.to_numeric(df_new[col], errors='coerce')

        # ignore columns that cannot be converted at all
        if converted.dropna().empty:
            continue

        # check only non-NA values
        non_na = converted.dropna()

        # if all values are integers
        if (non_na % 1 == 0).all():
            # if there are NA values, keep as float64 (int64 cannot store NA)
            if converted.isna().any():
                print(f"Column '{col}' has NA values, converting to float64 to preserve them.")
                df_new[col] = converted.astype(np.float64)
            else:
                df_new[col] = converted.astype(np.int64)
        else:
            df_new[col] = converted.astype(np.float64)

    return df_new

anime_filtered = convert_to_numeric_64(anime_filtered)

Column 'name' has NA values, converting to float64 to preserve them.
Column 'english_name' has NA values, converting to float64 to preserve them.
Column 'japanese_name' has NA values, converting to float64 to preserve them.
Column 'episodes' has NA values, converting to float64 to preserve them.
Column 'aired' has NA values, converting to float64 to preserve them.
Column 'ranked' has NA values, converting to float64 to preserve them.
Column 'score_10' has NA values, converting to float64 to preserve them.
Column 'score_9' has NA values, converting to float64 to preserve them.
Column 'score_8' has NA values, converting to float64 to preserve them.
Column 'score_7' has NA values, converting to float64 to preserve them.
Column 'score_6' has NA values, converting to float64 to preserve them.
Column 'score_5' has NA values, converting to float64 to preserve them.
Column 'score_4' has NA values, converting to float64 to preserve them.
Column 'score_3' has NA values, converting to float64 to preserve them.
Column 'score_2' has NA values, converting to float64 to preserve them.
Column 'score_1' has NA values, converting to float64 to preserve them.

In [ ]:
for col in anime_filtered.columns:
    if anime_filtered[col].dtype != 'int64' and anime_filtered[col].dtype != 'float64':
        print(f"Col - {col}: {anime_filtered[col].unique()}")

Col - genres: ['Sci-Fi, Music, Fantasy'
 'Action, Sci-Fi, Adventure, Mystery, Drama, Shoujo'
 'Demons, Historical, Military, Romance, Seinen, Supernatural' ...
 'Sci-Fi, Space, Drama' 'Harem, Mystery, Romance, Fantasy, Josei'
 'Action, Adventure, Supernatural, Vampire, Shounen']
Col - type: ['Music' 'TV' 'Special' 'OVA' 'Movie' 'ONA' 'Unknown']
Col - premiered: ['Unknown' 'Spring 2006' 'Fall 2010' 'Spring 2009' 'Fall 1995' 'Fall 2001'
 'Fall 1980' 'Fall 1975' 'Summer 2014' 'Summer 2015' 'Spring 1974'
 'Fall 2004' 'Fall 2016' 'Summer 2013' 'Fall 2014' 'Summer 2012'
 'Winter 2005' 'Fall 2006' 'Spring 2020' 'Winter 1988' 'Fall 2012'
 'Spring 2017' 'Fall 2008' 'Spring 2011' 'Spring 1996' 'Spring 2012'
 'Summer 2017' 'Spring 2003' 'Winter 2007' 'Spring 1998' 'Spring 2016'
 'Summer 2020' 'Summer 2002' 'Fall 2009' 'Summer 2004' 'Fall 2005'
 'Summer 2021' 'Spring 2008' 'Winter 2012' 'Summer 2018' 'Fall 2017'
 'Spring 1988' 'Fall 2011' 'Spring 1991' 'Summer 2010' 'Fall 2007'
 'Winter 1990' 'Fall 1997' 'Fall 1984' 'Winter 2016' 'Fall 2019'
 'Spring 2014' 'Spring 2013' 'Spring 1970' 'Summer 2008' 'Spring 2001'
 'Winter 2001' 'Winter 2000' 'Fall 1996' 'Winter 2011' 'Spring 2019'
 'Fall 1994' 'Spring 2021' 'Spring 1992' 'Fall 1989' 'Fall 2018'
 'Winter 2013' 'Fall 2015' 'Winter 1996' 'Spring 1997' 'Winter 2004'
 'Spring 2010' 'Fall 1976' 'Summer 1988' 'Fall 1999' 'Winter 2010'
 'Winter 2009' 'Spring 1995' 'Spring 2018' 'Summer 1975' 'Winter 2008'
 'Fall 2000' 'Spring 2007' 'Fall 1978' 'Spring 2004' 'Fall 2020'
 'Winter 2014' 'Spring 1965' 'Fall 2013' 'Spring 1969' 'Winter 1978'
 'Summer 2011' 'Winter 1998' 'Winter 1999' 'Winter 2021' 'Winter 2017'
 'Spring 1987' 'Spring 1994' 'Winter 2019' 'Fall 1966' 'Summer 2019'
 'Winter 2015' 'Fall 1998' 'Summer 2016' 'Winter 1995' 'Winter 1977'
 'Summer 1972' 'Summer 2009' 'Spring 1972' 'Spring 1993' 'Summer 1976'
 'Winter 2018' 'Fall 1974' 'Summer 2001' 'Fall 1970' 'Winter 1980'
 'Fall 1977' 'Spring 1989' 'Summer 1995' 'Summer 2006' 'Summer 2000'
 'Winter 1982' 'Spring 2000' 'Fall 1982' 'Summer 1998' 'Spring 2005'
 'Spring 1984' 'Spring 1986' 'Summer 2005' 'Fall 2003' 'Fall 1983'
 'Summer 1965' 'Summer 2003' 'Summer 1986' 'Spring 1983' 'Spring 1985'
 'Winter 2003' 'Winter 2020' 'Fall 1987' 'Spring 2015' 'Spring 2002'
 'Fall 1993' 'Fall 1992' 'Spring 1990' 'Fall 1981' 'Winter 2002'
 'Winter 2006' 'Fall 1965' 'Summer 1982' 'Fall 1990' 'Spring 1999'
 'Winter 1987' 'Summer 1966' 'Spring 1982' 'Spring 1971' 'Summer 1974'
 'Winter 1973' 'Spring 1979' 'Fall 1973' 'Spring 1968' 'Summer 1994'
 'Summer 1983' 'Winter 1984' 'Winter 1997' 'Spring 1964' 'Fall 1968'
 'Fall 2002' 'Summer 2007' 'Fall 1979' 'Winter 1993' 'Summer 1987'
 'Fall 2021' 'Summer 1999' 'Winter 1994' 'Fall 1972' 'Summer 1990'
 'Fall 1991' 'Winter 1992' 'Fall 1988' 'Fall 1963' 'Spring 1976'
 'Summer 1985' 'Winter 1965' 'Spring 1977' 'Winter 1966' 'Spring 1980'
 'Fall 1971' 'Spring 1961' 'Winter 1983' 'Spring 1981' 'Winter 1972'
 'Fall 1986' 'Spring 1975' 'Winter 1974' 'Fall 1969' 'Spring 1978'
 'Summer 1980' 'Summer 1981' 'Spring 1973' 'Summer 1992' 'Summer 1984'
 'Winter 1970' 'Summer 1996' 'Winter 1971' 'Fall 1967' 'Winter 1981'
 'Spring 1967' 'Fall 1985' 'Winter 1979' 'Summer 1989' 'Winter 1986'
 'Winter 1975' 'Summer 1977' 'Winter 1976' 'Summer 1991' 'Summer 1978'
 'Winter 1967' 'Summer 1997' 'Winter 1989' 'Summer 1979' 'Summer 1970'
 'Winter 1963' 'Winter 1991' 'Winter 1968' 'Spring 1966' 'Winter 1985'
 'Winter 1969' 'Summer 1962' 'Summer 1967' 'Winter 1964' 'Summer 1964']
Col - producers: ['Unknown'
 'Dentsu, SKY Perfect Well Think, Fuji TV, Asmik Ace, Sony Music Entertainment'
 'Aniplex' ...
 'TBS, Grooove, Nichion, Exit Tunes, ONEMUSIC, Crunchyroll SC Anime Fund'
 'Genco, Movic, Warner Bros. Japan, KlockWorx, SoftBank Creative, MAGES., Hakuhodo DY Music & Pictures, FuRyu, Imagine'
 'Geneon Universal Entertainment, Frontier Works, Movic, AT-X, DAX Production, Showgate']
Col - licensors: ['Unknown' 'Funimation' 'NIS America, Inc.' 'Sentai Filmworks'
 'Central Park Media, Discotek Media' 'ADV Films' 'Discotek Media'
 'SoftCel Pictures' '4Kids Entertainment, Miramax Films'
 'Aniplex of America' 'ADV Films, Funimation'
 'Maiden Japan, Manga Entertainment, Bandai Visual USA'
 '4Kids Entertainment, Warner Bros. Japan'
 'The Pokemon Company International' 'VIZ Media' 'Ponycan USA'
 'Funimation, Central Park Media, Enoki Films' 'Nelvana'
 'Geneon Entertainment USA' 'NYAV Post, GKIDS'
 'ADV Films, Sentai Filmworks' 'Central Park Media' 'Maiden Japan'
 'Funimation, Bandai Entertainment, Kadokawa Pictures USA'
 'Bandai Entertainment, Discotek Media' 'Media Blasters' 'AnimEigo'
 'Discotek Media, Crunchyroll' 'Nozomi Entertainment'
 'Bandai Entertainment' 'Nozomi Entertainment, Central Park Media'
 'Bandai Entertainment, Manga Entertainment'
 'VIZ Media, Geneon Entertainment USA' 'ADV Films, Nozomi Entertainment'
 'Flatiron Film Company' 'Bandai Entertainment, Bandai Visual USA'
 'Walt Disney Studios' 'GKIDS' 'Nozomi Entertainment, Media Blasters'
 'Eleven Arts' 'Bandai, Sentai Filmworks' 'Sentai Filmworks, Urban Vision'
 'Funimation, Geneon Entertainment USA' 'Funimation, Crunchyroll'
 'Geneon Universal Entertainment' 'Saban Entertainment'
 'Sentai Filmworks, Geneon Entertainment USA'
 'Media Blasters, Kitty Media' 'Funimation, Bandai Entertainment'
 'Bandai Entertainment, Sentai Filmworks' 'Manga Entertainment'
 'Funimation, Kadokawa Pictures USA'
 'Discotek Media, Geneon Entertainment USA' 'Sentai Filmworks, NYAV Post'
 'Media Blasters, Discotek Media' 'Media Blasters, NYAV Post'
 'Kitty Media' 'Discotek Media, Urban Vision' 'ADV Films, AnimEigo'
 'Discotek Media, Manga Entertainment' 'VIZ Media, NYAV Post'
 'Bandai Visual USA' 'Geneon Universal Entertainment, Funimation'
 'Central Park Media, Maiden Japan' 'Funimation, 4Kids Entertainment'
 'Funimation, Discotek Media' 'Tokyopop' '4Kids Entertainment'
 'AnimEigo, Discotek Media' 'Dentsu Entertainment USA' 'Shout! Factory'
 'Flatiron Film Company, Geneon Entertainment USA' 'Crunchyroll'
 'Walt Disney Studios, GKIDS' 'VIZ Media, Discotek Media'
 'Funimation, Sentai Filmworks' 'Funimation, Tokyopop'
 'Marvel Entertainment' 'iQIYI' 'Saban Brands' 'Urban Vision'
 'Warner Bros. Pictures' 'VIZ Media, The Pokemon Company International'
 'ADV Films, Discotek Media' 'Bandai Entertainment, Media Blasters'
 'NuTech Digital, Central Park Media' 'JapanAnime'
 'Nozomi Entertainment, Bandai Entertainment'
 'VIZ Media, Flatiron Film Company' 'feel.' 'Cookie Jar Entertainment'
 'Netflix' 'Bandai Entertainment, Central Park Media'
 'Nozomi Entertainment, Kadokawa Pictures USA' 'Nelvana, Discotek Media'
 'ADV Films, Funimation, NYAV Post'
 'Funimation, Discotek Media, Geneon Entertainment USA'
 'Funimation, Aniplex of America'
 'Bandai Entertainment, Discotek Media, Bandai Visual USA'
 'Funimation, NBCUniversal Entertainment Japan' 'Funimation, NYAV Post'
 'ADV Films, Aniplex of America' 'Sentai Filmworks, Ponycan USA'
 'Discotek Media, Saban Entertainment'
 '4Kids Entertainment, Nintendo of America'
 '4Kids Entertainment, Enoki Films, Discotek Media'
 'Nozomi Entertainment, Maiden Japan' 'Kadokawa Pictures USA'
 'Sony Pictures Entertainment'
 'ADV Films, Funimation, Kadokawa Pictures USA' 'Funimation, Synch-Point'
 'NYAV Post' 'Aniplex of America, Geneon Entertainment USA'
 'Sentai Filmworks, Synch-Point' 'Nozomi Entertainment, Discotek Media'
 'Discotek Media, Tokyopop' 'Critical Mass Video'
 'Media Blasters, Discotek Media, NYAV Post, Manga Entertainment'
 'ADV Films, Media Blasters, Discotek Media'
 'VIZ Media, 4Kids Entertainment' 'Anime Midstream'
 '4Kids Entertainment, Discotek Media' 'Warner Bros. Japan'
 'Media Blasters, SoftCel Pictures' 'Pied Piper'
 'Bandai Entertainment, NYAV Post'
 'Maiden Japan, Geneon Entertainment USA'
 '4Kids Entertainment, Warner Bros. Pictures' 'Enoki Films' 'Hasbro'
 'Media Blasters, Sentai Filmworks' 'Media Blasters, Central Park Media'
 'Adult Source Media' 'NIS America, Inc., Aniplex of America'
 'NuTech Digital' 'NuTech Digital, Critical Mass Video'
 'Funimation, Bandai Entertainment, Geneon Entertainment USA' 'Active'
 'Bandai' 'Anchor Bay Films' 'ADV Films, Sentai Filmworks, Discotek Media'
 'Saban Entertainment, Flatiron Film Company' 'Cinelicious Pics'
 'Nozomi Entertainment, Media Blasters, NYAV Post'
 'Sony Pictures Entertainment, GKIDS'
 'VIZ Media, 4Kids Entertainment, The Pokemon Company International'
 'Funimation, Media Blasters' 'ADV Films, Funimation, OLM Digital'
 'VIZ Media, Sentai Filmworks' 'bilibili'
 'Sentai Filmworks, Saban Entertainment'
 'Nelvana, Discotek Media, Geneon Entertainment USA'
 'Funimation, Central Park Media' 'Funimation, Warner Bros. Japan, GKIDS'
 'Eleven Arts, Ponycan USA' 'Eleven Arts, DreamWorks'
 'Funimation, Discotek Media, Crunchyroll' 'Sentai Filmworks, Kadokawa'
 'Pioneer LDC' 'Discotek Media, Ponycan USA' 'Tokyopop, Maiden Japan'
 'Bandai Entertainment, Sentai Filmworks, NYAV Post'
 'ADV Films, VIZ Media, DiC Entertainment'
 'Media Blasters, Discotek Media, Tokyopop'
 'Central Park Media, Sentai Filmworks, Discotek Media'
 'Media Blasters, Discotek Media, NYAV Post' 'ADV Films, Maiden Japan'
 'B.CMAY PICTURES' 'ADV Films, Netflix'
 '4Kids Entertainment, Flatiron Film Company'
 'Bandai Entertainment, Media Blasters, Bandai Visual USA'
 'Media Blasters, Central Park Media, Discotek Media'
 'Central Park Media, NYAV Post' 'Super Techno Arts'
 'Eleven Arts, Shout! Factory' 'Warner Bros. Japan, Crunchyroll'
 'Voyager Entertainment' 'Ketchup Entertainment' 'Eleven Arts, NYAV Post'
 'Sony Pictures Entertainment, Discotek Media'
 'Aniplex of America, Crunchyroll' 'ADV Films, Media Blasters'
 'Nozomi Entertainment, NYAV Post'
 'Bandai Entertainment, Discotek Media, NYAV Post, Bandai Visual USA'
 'VIZ Media, Media Blasters, Sentai Filmworks, Geneon Entertainment USA'
 'Sentai Filmworks, Manga Entertainment'
 'Nozomi Entertainment, Geneon Entertainment USA' 'Synch-Point'
 'ADV Films, DiC Entertainment, Flatiron Film Company'
 'ADV Films, Bandai Entertainment, Discotek Media, Crunchyroll'
 'Aniplex of America, Manga Entertainment'
 'Media Blasters, Geneon Entertainment USA'
 'Maiden Japan, Bandai Visual USA'
 'Nozomi Entertainment, Bandai Entertainment, NYAV Post'
 'Central Park Media, Critical Mass Video'
 'Bandai Entertainment, Sentai Filmworks, Discotek Media'
 'ADV Films, Central Park Media' 'ADV Films, SoftCel Pictures'
 'Funimation, Manga Entertainment' 'Discotek Media, Bandai Visual USA'
 'Nozomi Entertainment, Bandai Visual USA'
 'Nelvana, NIS America, Inc., Geneon Entertainment USA'
 'NuTech Digital, Adult Source Media'
 'Walt Disney Studios, Hasbro, Saban Entertainment'
 'Bandai Entertainment, Aniplex of America'
 '4Kids Entertainment, The Pokemon Company International' 'Media Bank'
 'ADV Films, Central Park Media, Discotek Media'
 'Anchor Bay Films, Manga Entertainment' 'NYAV Post, Pied Piper'
 'ADV Films, Central Park Media, Sentai Filmworks'
 'Haoliners Animation League' 'ADV Films, Manga Entertainment'
 'Nozomi Entertainment, Crimson Star Media' 'Kadokawa'
 'Konami, 4Kids Entertainment' 'GKIDS, Manga Entertainment' 'Capcom'
 'Bandai Namco Games' 'Bandai Entertainment, Maiden Japan'
 'Sentai Filmworks, Crunchyroll' "Brain's Base, Discotek Media"
 'NuTech Digital, Kitty Media' 'Funimation, Nozomi Entertainment'
 'Media Blasters, Maiden Japan' 'ADV Films, Warner Bros. Japan'
 'ADV Films, Bandai Entertainment, Aniplex of America'
 'ADV Films, Discotek Media, Shout! Factory' 'Enoki Films, Urban Vision'
 'Funimation, Sentai Filmworks, Geneon Entertainment USA'
 'VIZ Media, Warner Bros. Pictures']
Col - studios: ['Wit Studio' 'Bones' 'J.C.Staff' ... 'Nippon Ramayana Film Co.'
 'Ajia-Do, Bandai Namco Pictures' 'Azeta Pictures']
Col - source: ['Music' 'Manga' 'Original' 'Visual novel' 'Game' 'Novel' 'Other'
 'Unknown' 'Light novel' 'Card game' 'Web manga' '4-koma manga'
 'Picture book' 'Book' 'Radio' 'Digital manga']
Col - duration: ['4 min.' '22 min. per ep.' '24 min. per ep.' '30 sec. per ep.'
 '20 min. per ep.' '24 min.' '26 min.' '23 min. per ep.' '5 min.'
 '3 min. per ep.' '7 min.' 'Unknown' '30 min. per ep.' '25 min. per ep.'
 '30 min.' '10 min.' '13 min.' '43 min.' '2 min.' '1 hr. 24 min.'
 '16 min. per ep.' '4 min. per ep.' '46 min.' '3 min.' '1 hr. 53 min.'
 '57 sec.' '5 min. per ep.' '8 min.' '47 min.' '1 hr. 38 min.' '1 min.'
 '1 min. per ep.' '1 hr. 21 min.' '1 hr. 39 min.' '1 hr. 20 min.'
 '9 min. per ep.' '25 min.' '51 min.' '14 min. per ep.' '1 hr. 14 min.'
 '43 min. per ep.' '1 hr. 40 min.' '30 sec.' '9 min.' '59 min.'
 '1 hr. 58 min.' '28 min.' '11 min. per ep.' '12 min. per ep.' '16 min.'
 '2 min. per ep.' '1 hr. 34 min.' '23 min.' '15 min. per ep.' '38 sec.'
 '40 min.' '32 min.' '15 min.' '1 hr. 32 min.' '1 hr. 8 min.'
 '1 hr. 15 min.' '1 hr. 31 min.' '17 min.' '38 min.' '1 hr. 56 min.'
 '1 hr.' '51 sec. per ep.' '15 sec.' '37 min. per ep.' '13 min. per ep.'
 '31 min.' '58 min.' '12 min.' '11 min.' '1 hr. 10 min.' '1 hr. 30 min.'
 '1 hr. 37 min.' '21 min.' '27 min. per ep.' '28 min. per ep.'
 '1 hr. 25 min.' '45 min. per ep.' '44 min.' '27 min.' '1 hr. 22 min.'
 '45 sec.' '53 min.' '29 min. per ep.' '1 hr. 11 min.' '20 min.'
 '1 hr. 44 min.' '36 min. per ep.' '1 hr. 50 min.' '1 hr. 23 min.'
 '1 hr. 9 min.' '41 min. per ep.' '26 min. per ep.' '48 min.' '29 min.'
 '1 hr. 45 min.' '45 min.' '41 sec.' '22 min.' '1 hr. 59 min.'
 '25 sec. per ep.' '52 min.' '33 min.' '47 min. per ep.' '55 min. per ep.'
 '10 min. per ep.' '34 min.' '7 min. per ep.' '6 min.' '8 min. per ep.'
 '1 hr. 35 min.' '14 min.' '50 min.' '1 hr. 54 min.' '18 min.'
 '44 sec. per ep.' '57 min.' '1 hr. 55 min.' '35 sec.' '46 min. per ep.'
 '19 min.' '35 sec. per ep.' '21 min. per ep.' '2 hr.' '34 min. per ep.'
 '28 sec.' '50 min. per ep.' '49 min. per ep.' '1 hr. 27 min.'
 '17 min. per ep.' '1 hr. 41 min.' '56 min.' '55 min.' '2 hr. 1 min.'
 '32 min. per ep.' '2 hr. 41 min.' '1 hr. 5 min.' '1 hr. 12 min.'
 '49 min.' '40 min. per ep.' '42 min. per ep.' '47 sec.' '1 hr. 13 min.'
 '1 hr. 7 min.' '34 sec. per ep.' '6 min. per ep.' '51 min. per ep.'
 '2 hr. 5 min.' '54 min.' '1 hr. 42 min.' '15 sec. per ep.'
 '1 hr. 17 min.' '35 min.' '1 hr. 51 min.' '2 hr. 33 min.'
 '33 min. per ep.' '1 hr. 18 min.' '54 min. per ep.' '1 hr. 29 min.'
 '1 hr. 46 min.' '2 hr. 6 min.' '31 sec.' '1 hr. 28 min.'
 '20 sec. per ep.' '41 min.' '1 hr. per ep.' '1 hr. 16 min.'
 '45 sec. per ep.' '1 hr. 38 min. per ep.' '18 min. per ep.' '42 sec.'
 '1 hr. 47 min.' '19 min. per ep.' '19 sec.' '1 hr. 36 min.'
 '1 hr. 3 min.' '51 sec.' '24 sec. per ep.' '2 hr. 10 min.'
 '57 sec. per ep.' '39 min.' '1 hr. 36 min. per ep.' '39 sec.'
 '35 min. per ep.' '1 hr. 14 min. per ep.' '26 sec. per ep.'
 '1 hr. 48 min.' '16 sec.' '36 sec.' '29 sec.' '1 hr. 2 min.'
 '42 sec. per ep.' '58 sec. per ep.' '33 sec.' '1 hr. 57 min.'
 '1 hr. 33 min.' '1 hr. 4 min.' '40 sec.' '24 sec.' '2 hr. 2 min.'
 '1 hr. 30 min. per ep.' '40 sec. per ep.' '1 hr. 43 min.' '2 hr. 20 min.'
 '44 min. per ep.' '12 sec.' '14 sec.' '10 sec.' '2 hr. 14 min.'
 '2 hr. 28 min.' '1 hr. 17 min. per ep.' '37 min.' '1 hr. 52 min.'
 '31 min. per ep.' '1 hr. 26 min.' '3 sec.' '1 hr. 49 min.' '42 min.'
 '37 sec.' '2 hr. 15 min.' '52 sec.' '21 sec. per ep.' '50 sec. per ep.'
 '54 sec.' '1 hr. 1 min.' '53 sec. per ep.' '53 min. per ep.'
 '1 hr. 19 min.' '39 min. per ep.' '1 hr. 35 min. per ep.'
 '52 min. per ep.' '46 sec.' '39 sec. per ep.' '2 hr. 3 min.'
 '33 sec. per ep.' '27 sec.' '1 hr. 16 min. per ep.' '32 sec. per ep.'
 '55 sec.' '2 hr. 40 min.' '1 hr. 6 min.' '36 sec. per ep.' '20 sec.'
 '38 min. per ep.' '2 hr. 30 min.' '2 hr. 4 min.' '2 hr. 17 min.'
 '41 sec. per ep.' '36 min.' '2 hr. 7 min.' '17 sec.' '37 sec. per ep.'
 '49 sec.' '2 hr. 21 min.' '1 hr. 27 min. per ep.' '14 sec. per ep.'
 '58 min. per ep.' '32 sec.' '43 sec. per ep.' '49 sec. per ep.'
 '2 hr. 11 min.' '2 hr. 27 min.' '28 sec. per ep.' '48 min. per ep.'
 '50 sec.' '2 hr. 16 min.' '1 hr. 24 min. per ep.' '1 hr. 9 min. per ep.'
 '6 sec. per ep.' '44 sec.' '22 sec. per ep.' '2 hr. 19 min.' '25 sec.'
 '2 hr. 47 min.' '57 min. per ep.' '56 sec. per ep.' '46 sec. per ep.'
 '6 sec.' '23 sec.' '2 hr. 8 min.' '2 hr. 43 min.' '34 sec.'
 '1 hr. 2 min. per ep.' '7 sec.' '13 sec.' '31 sec. per ep.'
 '2 hr. 32 min.' '22 sec.' '1 hr. 7 min. per ep.' '16 sec. per ep.'
 '18 sec. per ep.' '43 sec.' '2 hr. 36 min.' '2 hr. 42 min.'
 '1 hr. 5 min. per ep.' '38 sec. per ep.' '58 sec.'
 '1 hr. 11 min. per ep.' '2 hr. 12 min.' '10 sec. per ep.'
 '55 sec. per ep.' '1 hr. 15 min. per ep.' '23 sec. per ep.'
 '29 sec. per ep.' '21 sec.' '54 sec. per ep.' '12 sec. per ep.'
 '1 hr. 52 min. per ep.']
Col - rating: ['G - All Ages' 'R - 17+ (violence & profanity)'
 'PG-13 - Teens 13 or older' 'Rx - Hentai' 'R+ - Mild Nudity'
 'PG - Children' 'Unknown']

In [ ]:
animelist.columns

Index(['user_id', 'anime_id', 'rating', 'watching_status', 'watched_episodes'], dtype='object')

In [ ]:
anime_full = pd.merge(anime_filtered, animelist, on='anime_id', how='inner')

In [ ]:
anime_full.head()

,anime_id,name,score,genres,english_name,japanese_name,type,episodes,aired,premiered,...,score_6,score_5,score_4,score_3,score_2,score_1,user_id,rating_y,watching_status,watched_episodes
0,39769,NaN,6.70,"Sci-Fi, Music, Fantasy",NaN,NaN,Music,1.0,NaN,Unknown,...,134.0,64.0,17.0,13.0,7.0,4.0,314940,7,2,1
1,39769,NaN,6.70,"Sci-Fi, Music, Fantasy",NaN,NaN,Music,1.0,NaN,Unknown,...,134.0,64.0,17.0,13.0,7.0,4.0,282558,7,2,1
2,953,NaN,7.26,"Action, Sci-Fi, Adventure, Mystery, Drama, Shoujo",NaN,NaN,TV,11.0,NaN,Spring 2006,...,4360.0,2140.0,934.0,302.0,172.0,148.0,36280,0,3,2
3,953,NaN,7.26,"Action, Sci-Fi, Adventure, Mystery, Drama, Shoujo",NaN,NaN,TV,11.0,NaN,Spring 2006,...,4360.0,2140.0,934.0,302.0,172.0,148.0,204967,8,2,11
4,953,NaN,7.26,"Action, Sci-Fi, Adventure, Mystery, Drama, Shoujo",NaN,NaN,TV,11.0,NaN,Spring 2006,...,4360.0,2140.0,934.0,302.0,172.0,148.0,47618,0,4,5

In [ ]:
anime_full.shape

(576083, 39)

In [ ]:
anime_full.columns

Index(['anime_id', 'name', 'score', 'genres', 'english_name', 'japanese_name',
       'type', 'episodes', 'aired', 'premiered', 'producers', 'licensors',
       'studios', 'source', 'duration', 'rating_x', 'ranked', 'popularity',
       'members', 'favorites', 'watching', 'completed', 'on_hold', 'dropped',
       'plan_to_watch', 'score_10', 'score_9', 'score_8', 'score_7', 'score_6',
       'score_5', 'score_4', 'score_3', 'score_2', 'score_1', 'user_id',
       'rating_y', 'watching_status', 'watched_episodes'],
      dtype='object')

In [ ]:
anime_full.dtypes

anime_id              int64
name                float64
score               float64
genres               object
english_name        float64
japanese_name       float64
type                 object
episodes            float64
aired               float64
premiered            object
producers            object
licensors            object
studios              object
source               object
duration             object
rating_x             object
ranked              float64
popularity            int64
members               int64
favorites             int64
watching              int64
completed             int64
on_hold               int64
dropped               int64
plan_to_watch         int64
score_10            float64
score_9             float64
score_8             float64
score_7             float64
score_6             float64
score_5             float64
score_4             float64
score_3             float64
score_2             float64
score_1             float64
user_id               int64
rating_y              int64
watching_status       int64
watched_episodes      int64
dtype: object